package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Protection.LN_61850;

import com.fasterxml.jackson.annotation.JsonInclude;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Содержит в качестве атрибутов служебные логические узоы блокировок(CILO) 
 *  и  учета переключений.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:54 MSK 2020
 */

@Entity
@Table(name = "cilo")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class CILO extends Common_LN {


	public CILO(){

	}

}
