package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Protection.LN_61850;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.*;

/**
 * Дисианционная защита
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:54 MSK 2020
 */

@Entity
@Table(name = "pdis")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class PDIS extends Common_LN {

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pdis_settings_mrid")
	@JoinColumn(name = "pdis_settings_projectid")
	@JoinColumn(name = "pdis_settings_synthesizedschemenumber")
	@JoinColumn(name = "pdis_settings_schemascenarionumber")
	private PDIS_Settings PDIS_Settings;

	public PDIS_Settings getPDIS_Settings(){
		return this.PDIS_Settings;
	}

	@AssociationSetter(fieldName = "PDIS.PDIS_Settings", assocType = "ru.mpei.ltdb.model.CIMProfile.IEC61970.Base.Protection.LN_61850.PDIS_Settings", cardinality = "one")
	public void setPDIS_Settings(PDIS_Settings PDIS_Settings){
		this.PDIS_Settings = PDIS_Settings;
	}

	public PDIS(){

	}

}
