package ru.mpei.prob.model.CIMProfile.NTI;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Core.IdentifiedObject;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Domain.Money;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.*;

/**
 * Результаты расчета CAPEX/OPEX
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:49 MSK 2020
 */

@Entity
@Table(name = "capexopexcalculationresult")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class CapexOpexCalculationResult extends IdentifiedObject {
	@AttributeOverrides({
		@AttributeOverride(name="multiplier", column=@Column(name="capex_multiplier")),
		@AttributeOverride(name="unit", column=@Column(name="capex_unit")),
		@AttributeOverride(name="value", column=@Column(name="capex_value")),
	})
	private Money capex;
	@AttributeOverrides({
		@AttributeOverride(name="multiplier", column=@Column(name="opex_multiplier")),
		@AttributeOverride(name="unit", column=@Column(name="opex_unit")),
		@AttributeOverride(name="value", column=@Column(name="opex_value")),
	})
	private Money opex;


	public Money getCapex(){
		return this.capex;
	}

	@FieldSetter(fieldName = "CapexOpexCalculationResult.capex", fieldTypeStereotype = "CIMDatatype", fieldStereotype = "nti")
	public void setCapex(Money capex){
		this.capex = capex;
	}

	public Money getOpex(){
		return this.opex;
	}

	@FieldSetter(fieldName = "CapexOpexCalculationResult.opex", fieldTypeStereotype = "CIMDatatype", fieldStereotype = "nti")
	public void setOpex(Money opex){
		this.opex = opex;
	}

	public CapexOpexCalculationResult(){

	}

}
