package ru.mpei.prob.model.CIMProfile.NTI;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Generation.Production.GeneratingUnit;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.*;

/**
 * Накопитель электроэнергии
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Fri Dec 04 21:18:37 MSK 2020
 */

@Entity
@Table(name = "energystorage")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class EnergyStorage extends GeneratingUnit {
	/**
	 * Емкость АКБ, А*ч
	 */
	@Column(name="capacity", nullable = true)
	private Float capacity;
	/**
	 * Плотность вещества электролита, грамм / см^3
	 */
	@Column(name="electroliteDensity", nullable = true)
	private Float electroliteDensity;
	/**
	 * Прочие затраты
	 */
	@Column(name="priceAdditional", nullable = true)
	private Float priceAdditional;
	/**
	 * Кап.затраты на помещение
	 */
	@Column(name="priceLocation", nullable = true)
	private Float priceLocation;

	/**
	 * Накопитель ЭЭ
	 */
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chargecontroller_mrid")
	@JoinColumn(name = "chargecontroller_projectid")
	@JoinColumn(name = "chargecontroller_synthesizedschemenumber")
	@JoinColumn(name = "chargecontroller_schemascenarionumber")
	private ChargeController ChargeController;

	public Float getCapacity(){
		return this.capacity;
	}

	@FieldSetter(fieldName = "EnergyStorage.capacity", fieldTypeStereotype = "Primitive", fieldStereotype = "nti")
	public void setCapacity(Float capacity){
		this.capacity = capacity;
	}

	public Float getElectroliteDensity(){
		return this.electroliteDensity;
	}

	@FieldSetter(fieldName = "EnergyStorage.electroliteDensity", fieldTypeStereotype = "Primitive", fieldStereotype = "nti")
	public void setElectroliteDensity(Float electroliteDensity){
		this.electroliteDensity = electroliteDensity;
	}

	public Float getPriceAdditional(){
		return this.priceAdditional;
	}

	@FieldSetter(fieldName = "EnergyStorage.priceAdditional", fieldTypeStereotype = "Primitive", fieldStereotype = "nti")
	public void setPriceAdditional(Float priceAdditional){
		this.priceAdditional = priceAdditional;
	}

	public Float getPriceLocation(){
		return this.priceLocation;
	}

	@FieldSetter(fieldName = "EnergyStorage.priceLocation", fieldTypeStereotype = "Primitive", fieldStereotype = "nti")
	public void setPriceLocation(Float priceLocation){
		this.priceLocation = priceLocation;
	}

	public ChargeController getChargeController(){
		return this.ChargeController;
	}

	@AssociationSetter(fieldName = "EnergyStorage.ChargeController", assocType = "ru.mpei.ltdb.model.CIMProfile.NTI.ChargeController", cardinality = "one")
	public void setChargeController(ChargeController ChargeController){
		this.ChargeController = ChargeController;
	}

	public EnergyStorage(){

	}

}
