package ru.mpei.prob.model.CIMProfile.NTI;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Core.IdentifiedObject;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Вероятность сценария
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:50 MSK 2020
 */

@Entity
@Table(name = "scenariopossibility")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ScenarioPossibility extends IdentifiedObject {
	@Column(name="scenarioPossibility", nullable = true)
	private Float scenarioPossibility;


	public Float getScenarioPossibility(){
		return this.scenarioPossibility;
	}

	@FieldSetter(fieldName = "ScenarioPossibility.scenarioPossibility", fieldTypeStereotype = "Primitive", fieldStereotype = "nti")
	public void setScenarioPossibility(Float scenarioPossibility){
		this.scenarioPossibility = scenarioPossibility;
	}

	public ScenarioPossibility(){

	}

}
