package ru.mpei.prob.model.CIMProfile.NTI;
 
/**
 * Тип ПС: ТП, РП, РТП
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:50 MSK 2020
 */

public enum SubstationType{
	transformerSubstation,
	distributionSubstation,
	transformerAndDistributionSubstation
}
