package ru.mpei.prob.model.CIMProfile.IEC61970.Base.DiagramLayout;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Core.IdentifiedObject;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.*;

/**
 * A point in a given space defined by 3 coordinates and associated to a diagram 
 * object.  The coordinates may be positive or negative as the origin does 
 * not have to be in the corner of a diagram.  
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:51 MSK 2020
 */

@Entity
@Table(name = "diagramobjectpoint")
@JsonInclude(JsonInclude.Include.NON_NULL)
// surrogate inheritance
public class DiagramObjectPoint extends IdentifiedObject{
	/**
	 * The sequence position of the point, used for defining the order of points 
	 * for diagram objects acting as a polyline or polygon with more than one 
	 * point.
	 */
	@Column(name="sequenceNumber", nullable = true)
	private Integer sequenceNumber;
	/**
	 * The X coordinate of this point.
	 */
	@Column(name="xPosition", nullable = true)
	private Float xPosition;
	/**
	 * The Y coordinate of this point.
	 */
	@Column(name="yPosition", nullable = true)
	private Float yPosition;
	/**
	 * The Z coordinate of this point.
	 */
	@Column(name="zPosition", nullable = true)
	private Float zPosition;

	/**
	 * A diagram object can have 0 or more points to reflect its layout position, 
	 * routing (for polylines) or boundary (for polygons).
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "diagramobject_mrid")
	@JoinColumn(name = "diagramobject_projectid")
	@JoinColumn(name = "diagramobject_synthesizedschemenumber")
	@JoinColumn(name = "diagramobject_schemascenarionumber")
	private DiagramObject DiagramObject;
	/**
	 * A diagram object glue point is associated with 2 or more object points 
	 * that are considered to be 'glued' together.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "diagramobjectgluepoint_mrid")
	@JoinColumn(name = "diagramobjectgluepoint_projectid")
	@JoinColumn(name = "diagramobjectgluepoint_synthesizedschemenumber")
	@JoinColumn(name = "diagramobjectgluepoint_schemascenarionumber")
	private DiagramObjectGluePoint DiagramObjectGluePoint;

	public Integer getSequenceNumber(){
		return this.sequenceNumber;
	}

	@FieldSetter(fieldName = "DiagramObjectPoint.sequenceNumber", fieldTypeStereotype = "Primitive", fieldStereotype = "none")
	public void setSequenceNumber(Integer sequenceNumber){
		this.sequenceNumber = sequenceNumber;
	}

	public Float getXPosition(){
		return this.xPosition;
	}

	@FieldSetter(fieldName = "DiagramObjectPoint.xPosition", fieldTypeStereotype = "Primitive", fieldStereotype = "none")
	public void setXPosition(Float xPosition){
		this.xPosition = xPosition;
	}

	public Float getYPosition(){
		return this.yPosition;
	}

	@FieldSetter(fieldName = "DiagramObjectPoint.yPosition", fieldTypeStereotype = "Primitive", fieldStereotype = "none")
	public void setYPosition(Float yPosition){
		this.yPosition = yPosition;
	}

	public Float getZPosition(){
		return this.zPosition;
	}

	@FieldSetter(fieldName = "DiagramObjectPoint.zPosition", fieldTypeStereotype = "Primitive", fieldStereotype = "none")
	public void setZPosition(Float zPosition){
		this.zPosition = zPosition;
	}

	public DiagramObject getDiagramObject(){
		return this.DiagramObject;
	}

	@AssociationSetter(fieldName = "DiagramObjectPoint.DiagramObject", assocType = "ru.mpei.ltdb.model.CIMProfile.IEC61970.Base.DiagramLayout.DiagramObject", cardinality = "one")
	public void setDiagramObject(DiagramObject DiagramObject){
		this.DiagramObject = DiagramObject;
	}

	public DiagramObjectGluePoint getDiagramObjectGluePoint(){
		return this.DiagramObjectGluePoint;
	}

	@AssociationSetter(fieldName = "DiagramObjectPoint.DiagramObjectGluePoint", assocType = "ru.mpei.ltdb.model.CIMProfile.IEC61970.Base.DiagramLayout.DiagramObjectGluePoint", cardinality = "one")
	public void setDiagramObjectGluePoint(DiagramObjectGluePoint DiagramObjectGluePoint){
		this.DiagramObjectGluePoint = DiagramObjectGluePoint;
	}

	public DiagramObjectPoint(){

	}

}
