package ru.mpei.prob.model.CIMProfile.IEC61968.Customers;
 
/**
 * Kind of customer.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:50 MSK 2020
 */

public enum CustomerKind{
	residential,
	residentialAndCommercial,
	residentialAndStreetlight,
	residentialStreetlightOthers,
	residentialFarmService,
	commercialIndustrial,
	pumpingLoad,
	windMachine,
	energyServiceSupplier,
	energyServiceScheduler,
	internalUse,
	other
}
