package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Topology;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Core.ACDCTerminal;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Core.IdentifiedObject;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Core.ReportingGroup;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.*;
import java.util.List;

/**
 * Used to apply user standard names to topology buses. Typically used for 
 * "bus/branch" case generation. Associated with one or more terminals that 
 * are normally connected with the bus name.    The associated terminals are 
 * normally connected by non-retained switches. For a ring bus station configuration, 
 * all busbar terminals in the ring are typically associated.   For a breaker 
 * and a half scheme, both busbars would normally be associated.  For a ring 
 * bus, all busbars would normally be associated.  For a "straight" busbar 
 * configuration, normally only the main terminal at the busbar would be associated. 
 *  
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:54 MSK 2020
 */

@Entity
@Table(name = "busnamemarker")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class BusNameMarker extends IdentifiedObject {
	/**
	 * Priority of bus name marker for use as topology bus name.  Use 0 for don 
	 * t care.  Use 1 for highest priority.  Use 2 as priority is less than 1 
	 * and so on.
	 */
	@Column(name="priority", nullable = true)
	private Integer priority;

	/**
	 * The bus name marker used to name the bus (topological node).
	 */
	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.REMOVE}, fetch = FetchType.LAZY, mappedBy = "BusNameMarker")
	private List<ACDCTerminal> Terminal;
	/**
	 * The bus name markers that belong to this reporting group.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reportinggroup_mrid")
	@JoinColumn(name = "reportinggroup_projectid")
	@JoinColumn(name = "reportinggroup_synthesizedschemenumber")
	@JoinColumn(name = "reportinggroup_schemascenarionumber")
	private ReportingGroup ReportingGroup;

	public Integer getPriority(){
		return this.priority;
	}

	@FieldSetter(fieldName = "BusNameMarker.priority", fieldTypeStereotype = "Primitive", fieldStereotype = "none")
	public void setPriority(Integer priority){
		this.priority = priority;
	}

	@JsonIgnore
	public List<ACDCTerminal> getTerminal(){
		return this.Terminal;
	}

	@AssociationSetter(fieldName = "BusNameMarker.Terminal", assocType = "ru.mpei.ltdb.model.CIMProfile.IEC61970.Base.Core.ACDCTerminal", cardinality = "many")
	public void setTerminal(List<ACDCTerminal> Terminal){
		this.Terminal = Terminal;
	}

	public ReportingGroup getReportingGroup(){
		return this.ReportingGroup;
	}

	@AssociationSetter(fieldName = "BusNameMarker.ReportingGroup", assocType = "ru.mpei.ltdb.model.CIMProfile.IEC61970.Base.Core.ReportingGroup", cardinality = "one")
	public void setReportingGroup(ReportingGroup ReportingGroup){
		this.ReportingGroup = ReportingGroup;
	}

	public BusNameMarker(){

	}

}
