package ru.mpei.prob.model.CIMProfile.IEC61968.Common;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Core.IdentifiedObject;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Priority definition.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:50 MSK 2020
 */

@Entity
@Table(name = "priority")
@JsonInclude(JsonInclude.Include.NON_NULL)
// surrogate inheritance
public class Priority extends IdentifiedObject{
	/**
	 * Justification for 'rank'.
	 */
	@Column(name="justification", nullable = true)
	private String justification;
	/**
	 * Priority level; usually, lower number means high priority, but the details 
	 * are provided in 'type'.
	 */
	@Column(name="rank", nullable = true)
	private Integer rank;
	/**
	 * Type describing 'rank'; e.g., high, emergency, etc.
	 */
	@Column(name="type", nullable = true)
	private String type;


	public String getJustification(){
		return this.justification;
	}

	@FieldSetter(fieldName = "Priority.justification", fieldTypeStereotype = "Primitive", fieldStereotype = "none")
	public void setJustification(String justification){
		this.justification = justification;
	}

	public Integer getRank(){
		return this.rank;
	}

	@FieldSetter(fieldName = "Priority.rank", fieldTypeStereotype = "Primitive", fieldStereotype = "none")
	public void setRank(Integer rank){
		this.rank = rank;
	}

	public String getType(){
		return this.type;
	}

	@FieldSetter(fieldName = "Priority.type", fieldTypeStereotype = "Primitive", fieldStereotype = "none")
	public void setType(String type){
		this.type = type;
	}

	public Priority(){

	}

}
