package ru.mpei.prob.model.CIMProfile.IEC61968.Common;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Core.IdentifiedObject;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.*;

/**
 * General purpose street address information.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:50 MSK 2020
 */

@Entity
@Table(name = "streetaddress")
@JsonInclude(JsonInclude.Include.NON_NULL)
// surrogate inheritance
public class StreetAddress extends IdentifiedObject{
	/**
	 * Status of this address.
	 */
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_mrid")
	@JoinColumn(name = "status_projectid")
	@JoinColumn(name = "status_synthesizedschemenumber")
	@JoinColumn(name = "status_schemascenarionumber")
	private Status status;
	/**
	 * Street detail.
	 */
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "streetdetail_mrid")
	@JoinColumn(name = "streetdetail_projectid")
	@JoinColumn(name = "streetdetail_synthesizedschemenumber")
	@JoinColumn(name = "streetdetail_schemascenarionumber")
	private StreetDetail streetDetail;
	/**
	 * Town detail.
	 */
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "towndetail_mrid")
	@JoinColumn(name = "towndetail_projectid")
	@JoinColumn(name = "towndetail_synthesizedschemenumber")
	@JoinColumn(name = "towndetail_schemascenarionumber")
	private TownDetail townDetail;


	public Status getStatus(){
		return this.status;
	}

	@CompoundFieldSetter(fieldName = "StreetAddress.status", fieldType = "ru.mpei.ltdb.model.CIMProfile.IEC61968.Common.Status")
	public void setStatus(Status status){
		this.status = status;
	}

	public StreetDetail getStreetDetail(){
		return this.streetDetail;
	}

	@CompoundFieldSetter(fieldName = "StreetAddress.streetDetail", fieldType = "ru.mpei.ltdb.model.CIMProfile.IEC61968.Common.StreetDetail")
	public void setStreetDetail(StreetDetail streetDetail){
		this.streetDetail = streetDetail;
	}

	public TownDetail getTownDetail(){
		return this.townDetail;
	}

	@CompoundFieldSetter(fieldName = "StreetAddress.townDetail", fieldType = "ru.mpei.ltdb.model.CIMProfile.IEC61968.Common.TownDetail")
	public void setTownDetail(TownDetail townDetail){
		this.townDetail = townDetail;
	}

	public StreetAddress(){

	}

}
