package ru.mpei.prob.model.CIMProfile.IEC61968.Common;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Core.IdentifiedObject;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Telephone number.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:50 MSK 2020
 */

@Entity
@Table(name = "telephonenumber")
@JsonInclude(JsonInclude.Include.NON_NULL)
// surrogate inheritance
public class TelephoneNumber extends IdentifiedObject{
	/**
	 * Area or region code.
	 */
	@Column(name="areaCode", nullable = true)
	private String areaCode;
	/**
	 * (if applicable) City code.
	 */
	@Column(name="cityCode", nullable = true)
	private String cityCode;
	/**
	 * Country code.
	 */
	@Column(name="countryCode", nullable = true)
	private String countryCode;
	/**
	 * (if applicable) Extension for this telephone number.
	 */
	@Column(name="extension", nullable = true)
	private String extension;
	/**
	 * Main (local) part of this telephone number.
	 */
	@Column(name="localNumber", nullable = true)
	private String localNumber;


	public String getAreaCode(){
		return this.areaCode;
	}

	@FieldSetter(fieldName = "TelephoneNumber.areaCode", fieldTypeStereotype = "Primitive", fieldStereotype = "none")
	public void setAreaCode(String areaCode){
		this.areaCode = areaCode;
	}

	public String getCityCode(){
		return this.cityCode;
	}

	@FieldSetter(fieldName = "TelephoneNumber.cityCode", fieldTypeStereotype = "Primitive", fieldStereotype = "none")
	public void setCityCode(String cityCode){
		this.cityCode = cityCode;
	}

	public String getCountryCode(){
		return this.countryCode;
	}

	@FieldSetter(fieldName = "TelephoneNumber.countryCode", fieldTypeStereotype = "Primitive", fieldStereotype = "none")
	public void setCountryCode(String countryCode){
		this.countryCode = countryCode;
	}

	public String getExtension(){
		return this.extension;
	}

	@FieldSetter(fieldName = "TelephoneNumber.extension", fieldTypeStereotype = "Primitive", fieldStereotype = "none")
	public void setExtension(String extension){
		this.extension = extension;
	}

	public String getLocalNumber(){
		return this.localNumber;
	}

	@FieldSetter(fieldName = "TelephoneNumber.localNumber", fieldTypeStereotype = "Primitive", fieldStereotype = "none")
	public void setLocalNumber(String localNumber){
		this.localNumber = localNumber;
	}

	public TelephoneNumber(){

	}

}
