package ru.mpei.prob.model.CIMProfile.IEC61970.Base.AuxiliaryEquipment;

import com.fasterxml.jackson.annotation.JsonInclude;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * This class describe devices that transform a measured quantity into signals 
 * that can be presented at displays, used in control or be recorded.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:50 MSK 2020
 */

@Entity
@Table(name = "sensor")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Sensor extends AuxiliaryEquipment {


	public Sensor(){

	}

}
