package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Generation.Production;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Domain.Currency;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Domain.UnitMultiplier;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Domain.UnitSymbol;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;

/**
 * Cost, in units of currency, per quantity of heat generated.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:52 MSK 2020
 */

@Embeddable
@JsonInclude(JsonInclude.Include.NON_NULL)
public class CostPerHeatUnit {
	@Enumerated(EnumType.STRING)
	@Column(name = "denominatorMultiplier")
	private UnitMultiplier denominatorMultiplier;
	@Enumerated(EnumType.STRING)
	@Column(name = "denominatorUnit")
	private UnitSymbol denominatorUnit;
	@Enumerated(EnumType.STRING)
	@Column(name = "multiplier")
	private UnitMultiplier multiplier;
	@Enumerated(EnumType.STRING)
	@Column(name = "unit")
	private Currency unit;
	@Column(name="value", nullable = true)
	private Float value;


	public UnitMultiplier getDenominatorMultiplier(){
		return this.denominatorMultiplier;
	}

	@FieldSetter(fieldName = "CostPerHeatUnit.denominatorMultiplier", fieldTypeStereotype = "Enumeration", fieldStereotype = "none")
	public void setDenominatorMultiplier(UnitMultiplier denominatorMultiplier){
		this.denominatorMultiplier = denominatorMultiplier;
	}

	public UnitSymbol getDenominatorUnit(){
		return this.denominatorUnit;
	}

	@FieldSetter(fieldName = "CostPerHeatUnit.denominatorUnit", fieldTypeStereotype = "Enumeration", fieldStereotype = "none")
	public void setDenominatorUnit(UnitSymbol denominatorUnit){
		this.denominatorUnit = denominatorUnit;
	}

	public UnitMultiplier getMultiplier(){
		return this.multiplier;
	}

	@FieldSetter(fieldName = "CostPerHeatUnit.multiplier", fieldTypeStereotype = "Enumeration", fieldStereotype = "none")
	public void setMultiplier(UnitMultiplier multiplier){
		this.multiplier = multiplier;
	}

	public Currency getUnit(){
		return this.unit;
	}

	@FieldSetter(fieldName = "CostPerHeatUnit.unit", fieldTypeStereotype = "Enumeration", fieldStereotype = "none")
	public void setUnit(Currency unit){
		this.unit = unit;
	}

	public Float getValue(){
		return this.value;
	}

	@FieldSetter(fieldName = "CostPerHeatUnit.value", fieldTypeStereotype = "Primitive", fieldStereotype = "none")
	public void setValue(Float value){
		this.value = value;
	}

	public CostPerHeatUnit(){

	}

}
