package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Generation.Production;
 
/**
 * The source of controls for a generating unit.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:52 MSK 2020
 */

public enum GeneratorControlSource{
	unavailable,
	offAGC,
	onAGC,
	plantControl
}
