package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Generation.Production;
 
/**
 * Unit control modes.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:52 MSK 2020
 */

public enum GeneratorControlMode{
	setpoint,
	pulse
}
