package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Generation.Production;
 
/**
 * Specifies the capability of the hydro generating unit to convert energy 
 * as a generator or pump.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:52 MSK 2020
 */

public enum HydroEnergyConversionKind{
	generator,
	pumpAndGenerator
}
