package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Generation.Production;

import com.fasterxml.jackson.annotation.JsonInclude;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * A nuclear generating unit.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:52 MSK 2020
 */

@Entity
@Table(name = "nucleargeneratingunit")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class NuclearGeneratingUnit extends GeneratingUnit {


	public NuclearGeneratingUnit(){

	}

}
