package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Generation.Production;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * A solar thermal generating unit.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:52 MSK 2020
 */

@Entity
@Table(name = "solargeneratingunit")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class SolarGeneratingUnit extends GeneratingUnit {
	/**
	 * Кап.затраты на освоение территории
	 */
	@Column(name="priceLocation", nullable = true)
	private Float priceLocation;
	/**
	 * Кап.затраты на разработку проекта
	 */
	@Column(name="priceProject", nullable = true)
	private Float priceProject;
	/**
	 * Стоимость солнечных панелей
	 */
	@Column(name="priceSunPanel", nullable = true)
	private Float priceSunPanel;


	public Float getPriceLocation(){
		return this.priceLocation;
	}

	@FieldSetter(fieldName = "SolarGeneratingUnit.priceLocation", fieldTypeStereotype = "Primitive", fieldStereotype = "nti")
	public void setPriceLocation(Float priceLocation){
		this.priceLocation = priceLocation;
	}

	public Float getPriceProject(){
		return this.priceProject;
	}

	@FieldSetter(fieldName = "SolarGeneratingUnit.priceProject", fieldTypeStereotype = "Primitive", fieldStereotype = "nti")
	public void setPriceProject(Float priceProject){
		this.priceProject = priceProject;
	}

	public Float getPriceSunPanel(){
		return this.priceSunPanel;
	}

	@FieldSetter(fieldName = "SolarGeneratingUnit.priceSunPanel", fieldTypeStereotype = "Primitive", fieldStereotype = "nti")
	public void setPriceSunPanel(Float priceSunPanel){
		this.priceSunPanel = priceSunPanel;
	}

	public SolarGeneratingUnit(){

	}

}
