package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Generation.Production;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.*;

/**
 * A wind driven generating unit.  May be used to represent a single turbine 
 * or an aggregation.  
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:53 MSK 2020
 */

@Entity
@Table(name = "windgeneratingunit")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class WindGeneratingUnit extends GeneratingUnit {
	/**
	 * The kind of wind generating unit
	 */
	@Enumerated(EnumType.STRING)
	@Column(name = "windGenUnitType")
	private WindGenUnitKind windGenUnitType;


	public WindGenUnitKind getWindGenUnitType(){
		return this.windGenUnitType;
	}

	@FieldSetter(fieldName = "WindGeneratingUnit.windGenUnitType", fieldTypeStereotype = "Enumeration", fieldStereotype = "none")
	public void setWindGenUnitType(WindGenUnitKind windGenUnitType){
		this.windGenUnitType = windGenUnitType;
	}

	public WindGeneratingUnit(){

	}

}
