package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Faults;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Core.IdentifiedObject;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.*;
import java.util.List;

/**
 * Type of cause of the fault.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:52 MSK 2020
 */

@Entity
@Table(name = "faultcausetype")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class FaultCauseType extends IdentifiedObject {

	/**
	 * All types of fault cause.
	 */
	@ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.REMOVE}, fetch = FetchType.LAZY, mappedBy = "FaultCauseTypes")
	private List<Fault> Faults;

	@JsonIgnore
	public List<Fault> getFaults(){
		return this.Faults;
	}

	@AssociationSetter(fieldName = "FaultCauseType.Faults", assocType = "ru.mpei.ltdb.model.CIMProfile.IEC61970.Base.Faults.Fault", cardinality = "many")
	public void setFaults(List<Fault> Faults){
		this.Faults = Faults;
	}

	public FaultCauseType(){

	}

}
