package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Meas;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Core.IdentifiedObject;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Specifies one limit value for a Measurement. A Measurement typically has 
 * several limits that are kept together by the LimitSet class. The actual 
 * meaning and use of a Limit instance (i.e., if it is an alarm or warning 
 * limit or if it is a high or low limit) is not captured in the Limit class. 
 * However the name of a Limit instance may indicate both meaning and use.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:53 MSK 2020
 */

@Entity
@Table(name = "limit")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Limit extends IdentifiedObject {


	public Limit(){

	}

}
