package ru.mpei.prob.model.CIMProfile.IEC61970.Base.DC;
 
/**
 * The operating mode of an HVDC bipole.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:50 MSK 2020
 */

public enum DCConverterOperatingModeKind{
	bipolar,
	monopolarMetallicReturn,
	monopolarGroundReturn
}
