package ru.mpei.prob.model.CIMProfile.IEC61970.Base.DC;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Core.SubGeographicalRegion;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.*;

/**
 * Overhead lines and/or cables connecting two or more HVDC substations.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:51 MSK 2020
 */

@Entity
@Table(name = "dcline")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class DCLine extends DCEquipmentContainer {

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "region_mrid")
	@JoinColumn(name = "region_projectid")
	@JoinColumn(name = "region_synthesizedschemenumber")
	@JoinColumn(name = "region_schemascenarionumber")
	private SubGeographicalRegion Region;

	public SubGeographicalRegion getRegion(){
		return this.Region;
	}

	@AssociationSetter(fieldName = "DCLine.Region", assocType = "ru.mpei.ltdb.model.CIMProfile.IEC61970.Base.Core.SubGeographicalRegion", cardinality = "one")
	public void setRegion(SubGeographicalRegion Region){
		this.Region = Region;
	}

	public DCLine(){

	}

}
