package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Protection;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Core.IdentifiedObject;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Domain.Seconds;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Wires.ProtectedSwitch;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.*;

/**
 * A reclose sequence (open and close) is defined for each possible reclosure 
 * of a breaker.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:54 MSK 2020
 */

@Entity
@Table(name = "reclosesequence")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class RecloseSequence extends IdentifiedObject {
	/**
	 * Indicates the time lapse before the reclose step will execute a reclose.
	 */
	@AttributeOverrides({
		@AttributeOverride(name="multiplier", column=@Column(name="recloseDelay_multiplier")),
		@AttributeOverride(name="unit", column=@Column(name="recloseDelay_unit")),
		@AttributeOverride(name="value", column=@Column(name="recloseDelay_value")),
	})
	private Seconds recloseDelay;
	/**
	 * Indicates the ordinal position of the reclose step relative to other steps 
	 * in the sequence.
	 */
	@Column(name="recloseStep", nullable = true)
	private Integer recloseStep;

	/**
	 * A breaker may have zero or more automatic reclosures after a trip occurs.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "protectedswitch_mrid")
	@JoinColumn(name = "protectedswitch_projectid")
	@JoinColumn(name = "protectedswitch_synthesizedschemenumber")
	@JoinColumn(name = "protectedswitch_schemascenarionumber")
	private ProtectedSwitch ProtectedSwitch;

	public Seconds getRecloseDelay(){
		return this.recloseDelay;
	}

	@FieldSetter(fieldName = "RecloseSequence.recloseDelay", fieldTypeStereotype = "CIMDatatype", fieldStereotype = "none")
	public void setRecloseDelay(Seconds recloseDelay){
		this.recloseDelay = recloseDelay;
	}

	public Integer getRecloseStep(){
		return this.recloseStep;
	}

	@FieldSetter(fieldName = "RecloseSequence.recloseStep", fieldTypeStereotype = "Primitive", fieldStereotype = "none")
	public void setRecloseStep(Integer recloseStep){
		this.recloseStep = recloseStep;
	}

	public ProtectedSwitch getProtectedSwitch(){
		return this.ProtectedSwitch;
	}

	@AssociationSetter(fieldName = "RecloseSequence.ProtectedSwitch", assocType = "ru.mpei.ltdb.model.CIMProfile.IEC61970.Base.Wires.ProtectedSwitch", cardinality = "one")
	public void setProtectedSwitch(ProtectedSwitch ProtectedSwitch){
		this.ProtectedSwitch = ProtectedSwitch;
	}

	public RecloseSequence(){

	}

}
