package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Wires;
 
/**
 * Kind of Asynchronous Machine.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:54 MSK 2020
 */

public enum AsynchronousMachineKind{
	generator,
	motor
}
