package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Wires;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Core.ConductingEquipment;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * A conductor, or group of conductors, with negligible impedance, that serve 
 * to connect other conducting equipment within a single substation and are 
 * modelled with a single logical terminal.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:54 MSK 2020
 */

@Entity
@Table(name = "connector")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Connector extends ConductingEquipment {


	public Connector(){

	}

}
