package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Wires;

import com.fasterxml.jackson.annotation.JsonInclude;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * A manually operated or motor operated mechanical switching device used 
 * for isolating a circuit or equipment from ground.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:55 MSK 2020
 */

@Entity
@Table(name = "grounddisconnector")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class GroundDisconnector extends Switch {


	public GroundDisconnector(){

	}

}
