package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Wires;

import com.fasterxml.jackson.annotation.JsonInclude;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * A point where one or more conducting equipments are connected with zero 
 * resistance.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:55 MSK 2020
 */

@Entity
@Table(name = "junction")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Junction extends Connector {


	public Junction(){

	}

}
