package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Wires;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Core.EquipmentContainer;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Core.SubGeographicalRegion;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.*;

/**
 * Contains equipment beyond a substation belonging to a power transmission 
 * line. 
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:55 MSK 2020
 */

@Entity
@Table(name = "line")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Line extends EquipmentContainer {

	/**
	 * The lines within the sub-geographical region.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "region_mrid")
	@JoinColumn(name = "region_projectid")
	@JoinColumn(name = "region_synthesizedschemenumber")
	@JoinColumn(name = "region_schemascenarionumber")
	private SubGeographicalRegion Region;

	public SubGeographicalRegion getRegion(){
		return this.Region;
	}

	@AssociationSetter(fieldName = "Line.Region", assocType = "ru.mpei.ltdb.model.CIMProfile.IEC61970.Base.Core.SubGeographicalRegion", cardinality = "one")
	public void setRegion(SubGeographicalRegion Region){
		this.Region = Region;
	}

	public Line(){

	}

}
