package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Wires;
 
/**
 * The mode of operation for a Petersen coil.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:55 MSK 2020
 */

public enum PetersenCoilModeKind{
	fixed,
	manual,
	automaticPositioning
}
