package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Wires;
 
/**
 * The configuration of phase connections for a single terminal device such 
 * as a load or capactitor.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:55 MSK 2020
 */

public enum PhaseShuntConnectionKind{
	D,
	Y,
	Yn,
	I
}
