package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Wires;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.*;

/**
 * A transformer phase shifting tap model that controls the phase angle difference 
 * across the power transformer and potentially the active power flow through 
 * the power transformer.  This phase tap model may also impact the voltage 
 * magnitude.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:55 MSK 2020
 */

@Entity
@Table(name = "phasetapchanger")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class PhaseTapChanger extends TapChanger {

	/**
	 * Phase tap changer associated with this transformer end.
	 */
	@OneToOne(cascade = {CascadeType.PERSIST, CascadeType.REMOVE}, fetch = FetchType.LAZY, mappedBy = "PhaseTapChanger")
	private TransformerEnd TransformerEnd;

	@JsonIgnore
	public TransformerEnd getTransformerEnd(){
		return this.TransformerEnd;
	}

	@AssociationSetter(fieldName = "PhaseTapChanger.TransformerEnd", assocType = "ru.mpei.ltdb.model.CIMProfile.IEC61970.Base.Wires.TransformerEnd", cardinality = "one")
	public void setTransformerEnd(TransformerEnd TransformerEnd){
		this.TransformerEnd = TransformerEnd;
	}

	public PhaseTapChanger(){

	}

}
