package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Wires;

import com.fasterxml.jackson.annotation.JsonInclude;
import ru.mpei.prob.model.CIMProfile.IEC61970.Base.Domain.AngleDegrees;
import ru.mpei.prob.model.CIMProfile.ResourceAnnotations.*;

import javax.persistence.*;

/**
 * Describes each tap step in the phase tap changer tabular curve.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:55 MSK 2020
 */

@Entity
@Table(name = "phasetapchangertablepoint")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class PhaseTapChangerTablePoint extends TapChangerTablePoint {
	/**
	 * The angle difference in degrees.
	 */
	@AttributeOverrides({
		@AttributeOverride(name="multiplier", column=@Column(name="angle_multiplier")),
		@AttributeOverride(name="unit", column=@Column(name="angle_unit")),
		@AttributeOverride(name="value", column=@Column(name="angle_value")),
	})
	private AngleDegrees angle;

	/**
	 * The points of this table.
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "phasetapchangertable_mrid")
	@JoinColumn(name = "phasetapchangertable_projectid")
	@JoinColumn(name = "phasetapchangertable_synthesizedschemenumber")
	@JoinColumn(name = "phasetapchangertable_schemascenarionumber")
	private PhaseTapChangerTable PhaseTapChangerTable;

	public AngleDegrees getAngle(){
		return this.angle;
	}

	@FieldSetter(fieldName = "PhaseTapChangerTablePoint.angle", fieldTypeStereotype = "CIMDatatype", fieldStereotype = "none")
	public void setAngle(AngleDegrees angle){
		this.angle = angle;
	}

	public PhaseTapChangerTable getPhaseTapChangerTable(){
		return this.PhaseTapChangerTable;
	}

	@AssociationSetter(fieldName = "PhaseTapChangerTablePoint.PhaseTapChangerTable", assocType = "ru.mpei.ltdb.model.CIMProfile.IEC61970.Base.Wires.PhaseTapChangerTable", cardinality = "one")
	public void setPhaseTapChangerTable(PhaseTapChangerTable PhaseTapChangerTable){
		this.PhaseTapChangerTable = PhaseTapChangerTable;
	}

	public PhaseTapChangerTablePoint(){

	}

}
