package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Wires;
 
/**
 * Enumeration of single phase identifiers. Allows designation of single phases 
 * for both transmission and distribution equipment, circuits and loads.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:56 MSK 2020
 */

public enum SinglePhaseKind{
	A,
	B,
	C,
	N,
	s1,
	s2
}
