package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Wires;
 
/**
 * Synchronous machine type.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:56 MSK 2020
 */

public enum SynchronousMachineKind{
	generator,
	condenser,
	generatorOrCondenser,
	motor,
	generatorOrMotor,
	motorOrCondenser,
	generatorOrCondenserOrMotor
}
