package ru.mpei.prob.model.CIMProfile.IEC61970.Base.Domain;
 
/**
 * The units defined for usage in the CIM.
 * Generated by "JavaBeansGenerator" project.
 * @author Said Nukhulov  (nukhulovsm@yandex.ru)
 * @created Sat Dec 05 15:18:51 MSK 2020
 */

public enum UnitSymbol{
	VA,
	W,
	VAr,
	VAh,
	Wh,
	VArh,
	V,
	ohm,
	A,
	F,
	H,
	degC,
	s,
	min,
	h,
	deg,
	rad,
	J,
	N,
	S,
	none,
	Hz,
	g,
	Pa,
	m,
	m2,
	m3
}
